name: skipatomenv

channels:
  - conda-forge

dependencies:
  - python=3.6
  - pip
  - pip:
      - pymatgen==2021.2.8.1
      - numpy==1.18.5
      - tqdm==4.61.1
      - pandas==1.1.5
      - tensorflow==2.3.2
